### ISSUE TITLE
possibly to remove the `host/` prefix

### ISSUE THREAD

**Issue by wey-gu** [AshleyScirra/servefolder.dev#2]
This will prevent it from serving an HTML file that refers to other files with relative paths.

make the current `/` into `_config/` or?

**Comment by AshleyScirra** [comment]
The host prefix shouldn't prevent serving an HTML file that refers to other files with relative paths. What do you mean by that? What is actually not working?

**Comment by wey-gu** [comment]
Sorry for the late response, not sure, if it's my incorrect understanding:
- use servefolder.dev to browse foo/ with index.html and fav.png picture
- the URL of index.html will go to servefolder.dev/host/index.html
- the fav.png ref in index.html(hugo ssg site/page) is somehow actually servefolder.dev/fav.png instead of servefolder.dev/host/fav.png, thus it's broken.
Thanks.

**Comment by AshleyScirra** [comment]
My own tests using a favicon work fine. `<link rel="icon" href="icon.png">` fetches relative to the HTML page, which works on servefolder.dev.

I guess some origin-relative paths like `/icon.png` won't work. But I don't think there's a good solution to that case. The folder picker page needs to be somewhere, and the origin root seems to make sense; pages can be designed to use relative URLs which will work; and it's hard to see how multiple hosts could be supported that way. I've added a new descriptive section on limitations which covers that, so I think that's all to be done about this for now.
