### ISSUE TITLE
You cannot open files and folders in second-level subfolders

### ISSUE THREAD

**Issue by el3um4s** [AshleyScirra/servefolder.dev#3]
I tried to open a local version of my repository ([link](https://github.com/el3um4s/construct-demo)). I can only read one level of subfolders.

Example: [testServeFolder.zip](https://github.com/AshleyScirra/servefolder.dev/files/7864327/testServeFolder.zip)

```
testServeFolder/
       you-can-read-me.txt
       first-subfolder/
              you-can-read-me.txt
              second-subfolder/
                     you-can-NOT-read-me.txt
```

In the servefolder.dev console there is this error:

```console
index.js:239 Unable to serve file 'first-subfolder/first-subfolder/second-subfolder/you-can-NOT-read-me.txt':  DOMException: A requested file or directory could not be found at the time an operation was processed.
```

In the host there is this error:

![image](https://user-images.githubusercontent.com/23579630/149370205-b9965bb4-9b78-4558-a414-f259addf19e2.png)

**Comment by AshleyScirra** [comment]
It looks like the directory listing creates an incorrect link with `first-subfolder` repeated twice:

`https://servefolder.dev/host/first-subfolder/first-subfolder/second-subfolder/you-can-NOT-read-me.txt`

If you use the right link it works and serves the file content:

`https://servefolder.dev/host/first-subfolder/second-subfolder/you-can-NOT-read-me.txt`

So it looks like just an issue with the default directory listing page.

**Comment by el3um4s** [comment]
Thank you very much 😄

**Comment by AshleyScirra** [comment]
Should work now - clear cache to make sure it updates if you try again.
