### ISSUE TITLE
Can't Use it reach C3 addon.json

### ISSUE THREAD

**Issue by XHXIAIEIN** [AshleyScirra/servefolder.dev#7]
I downloaded `c3-theme-sdk-v1-0-1.zip`  from [addon-sdk](https://www.construct.net/en/make-games/manuals/addon-sdk) and extracted it to a folder. then  I try to use C3 debug mode to [Add dev addon](https://www.construct.net/en/make-games/manuals/addon-sdk/guide/using-developer-mode), but I can't use `https://servefolder.dev/host/addon.json` to add dev addon

![Snipaste_2022-06-02_22-57-58](https://user-images.githubusercontent.com/45864744/171658929-56159268-f3bf-4dd0-b94f-727c622a255f.png)

![Snipaste_2022-06-02_22-56-22](https://user-images.githubusercontent.com/45864744/171658659-fb49ec5d-29d0-4f20-a585-c7de6edc3c2b.png)

![Snipaste_2022-06-02_22-56-32](https://user-images.githubusercontent.com/45864744/171658670-26128b84-0666-4530-9554-cc33dbed73bd.png)

**Comment by AshleyScirra** [comment]
This is due to the Content Security Policy of Construct. Use a HTTP server running on localhost instead.
