### ISSUE TITLE
I serve a js file, but it cannot be load on other sites

### ISSUE THREAD

**Issue by pansong291** [AshleyScirra/servefolder.dev#8]
I browse a site, and I open the devTools, type the code as below:
```javascript
const script = document.createElement('script')
script.src = 'https://servefolder.dev/host/js/tampermonkey/test-helper.js?t=1691228538502'
script.onload = () => console.log('loaded')
document.head.append(script)
```
And then, I get an error, like this:
```
GET https://servefolder.dev/host/js/tampermonkey/test-helper.js?t=1691228538502 net::ERR_ABORTED 404
```
But this code can be loaded successfully at the `servefolder.dev` host.
I have no idea about this, Is there any solution?

**Comment by AshleyScirra** [comment]
I don't think a random request from dev tools on another site will go through a Service Worker, so that can't work.
