### ISSUE TITLE
Fails to serve if URL contains hashtag

### ISSUE THREAD

**Issue by zznidar** [AshleyScirra/servefolder.dev#9]
An URL can contain the `#` character followed by an identifier. In such cases, user will be scrolled down to the identified element. 

However, servefolder.dev fails to serve a file if there's hash at the end (only if the URL goes to a different page).

## Repro steps:
1. Unzip the attached folder and serve it with servefolder.dev
2. Open index2.html
3. Click on the link `here`

## Actual result:
```
File not found
The host 'host13' was not able to return a file for the path 'index1.html#about'. Check the file exists in the folder you chose to serve.
```

## Expected result:
Just the same way servefolder strips `?` queries, it should also strip `#` hashes when doing file lookup. Since hashes only refer to on-page elements, they are normally not sent to the server by the browser.

Interestingly, if user is already on the same page, then the hash-link works normally (open index1.html and click on the link `expected`).

## Browser info:
Firefox 129.0.1, Windows 10

[URLhash_bugreport.zip](https://github.com/user-attachments/files/16625157/URLhash_bugreport.zip)

**Comment by AshleyScirra** [comment]
Should be fixed in [this commit](https://github.com/AshleyScirra/servefolder.dev/commit/e1472e496832abff99227027833c25bbcf38e038). The change is live on servefolder.dev, but you may need to clear your cache to get it to update.
